### ISSUE TITLE
SuperController knowledgebase not accessable

### ISSUE THREAD

**Issue by Fluqz** [aolsenjazz/super-controller#11]
Hey, the documentation page is currently not accessable https://help.supercontroller.net/books/setup. 

Would be great if you could fix that :)

Thanks in advance

**Comment by aolsenjazz** [comment]
Hey, happy to fix. Just need to whip up a new server - should be able to Weds or thurs.

I should also mention - docs are pretty slim. As this project has been super iterative, I haven’t quite know what knowledge and guides to provide.

it would be a big help if you would follow up here down the line with any information or guides you’d like to see on the help website.

**Comment by aolsenjazz** [comment]
Docs website is back up. Please let me know what, if any, information I can add!

**Comment by aolsenjazz** [comment]
Closing this issue in a week, pending feedback on docs.
